#lang racket/base

(provide (struct-out program)

         (struct-out stmt-declare)
         (struct-out stmt-assign)
         (struct-out stmt-cast)
         (struct-out stmt-input)
         (struct-out stmt-visible)
         (struct-out stmt-loop)
         (struct-out stmt-if)
         (struct-out stmt-switch)
         (struct-out switch-case)
         (struct-out mebbe-branch)
         (struct-out stmt-function-def)
         (struct-out stmt-method-def)
         (struct-out stmt-return)
         (struct-out stmt-break)
         (struct-out stmt-object-def)
         (struct-out stmt-slot-set)
         (struct-out stmt-expr)

         (struct-out expr-ident)
         (struct-out expr-number)
         (struct-out expr-string)
         (struct-out expr-literal)
         (struct-out expr-binary)
         (struct-out expr-unary)
         (struct-out expr-variadic)
         (struct-out expr-call)
         (struct-out expr-method-call)
         (struct-out expr-slot)
         (struct-out expr-srs)
         (struct-out expr-type-default)
         (struct-out expr-clone)
         (struct-out expr-prototype)
         (struct-out expr-cast))

(struct program (version statements) #:transparent)

(struct stmt-declare (target init) #:transparent)
(struct stmt-assign (target expr) #:transparent)
(struct stmt-cast (target type-name) #:transparent)
(struct stmt-input (target) #:transparent)
(struct stmt-visible (exprs suppress-newline?) #:transparent)
(struct stmt-loop (label-open label-close update-var update-op cond-kind cond-expr body)
  #:transparent)
(struct stmt-if (condition then-branch mebbe-branches else-branch) #:transparent)
(struct stmt-switch (subject cases default) #:transparent)
(struct switch-case (match body) #:transparent)
(struct mebbe-branch (condition body) #:transparent)
(struct stmt-function-def (name args body) #:transparent)
(struct stmt-method-def (receiver name args body) #:transparent)
(struct stmt-return (expr) #:transparent)
(struct stmt-break () #:transparent)
(struct stmt-object-def (name parent mixins body) #:transparent)
(struct stmt-slot-set (object slot expr) #:transparent)
(struct stmt-expr (expr) #:transparent)

(struct expr-ident (name) #:transparent)
(struct expr-number (text) #:transparent)
(struct expr-string (text) #:transparent)
(struct expr-literal (value) #:transparent)
(struct expr-binary (op left right) #:transparent)
(struct expr-unary (op arg) #:transparent)
(struct expr-variadic (op args) #:transparent)
(struct expr-call (name args) #:transparent)
(struct expr-method-call (receiver name args) #:transparent)
(struct expr-slot (object slot) #:transparent)
(struct expr-srs (expr) #:transparent)
(struct expr-type-default (type-name) #:transparent)
(struct expr-clone (expr) #:transparent)
(struct expr-prototype (parent mixins) #:transparent)
(struct expr-cast (expr type-name) #:transparent)
