
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Fixed imageContainer;
	
	private global::Gtk.Label headerLabel;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Label inputLabel;
	
	private global::Gtk.Button fileButton;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView inputWindow;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.VBox box2;
	
	private global::Gtk.Label lexemeLabel;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.ScrolledWindow lexemeWindow;
	
	private global::Gtk.TreeView lexemeTree;
	
	private global::Gtk.VBox box3;
	
	private global::Gtk.Label symbolTableLabel;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.ScrolledWindow symbolTableWindow;
	
	private global::Gtk.TreeView symbolTableTree;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Button executeButton;
	
	private global::Gtk.Label consoleLabel;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Entry consoleEntry;
	
	private global::Gtk.Button consoleSubmit;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView consoleField;
	
	private global::Gtk.Statusbar lexerStatus;
	
	private global::Gtk.Statusbar creditsStatus;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(16));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.imageContainer = new global::Gtk.Fixed ();
		this.imageContainer.Name = "imageContainer";
		this.imageContainer.HasWindow = false;
		this.hbox1.Add (this.imageContainer);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.imageContainer]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.headerLabel = new global::Gtk.Label ();
		this.headerLabel.Name = "headerLabel";
		this.headerLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.hbox1.Add (this.headerLabel);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.headerLabel]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Homogeneous = true;
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.inputLabel = new global::Gtk.Label ();
		this.inputLabel.Name = "inputLabel";
		this.inputLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.hbox7.Add (this.inputLabel);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.inputLabel]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.fileButton = new global::Gtk.Button ();
		this.fileButton.CanFocus = true;
		this.fileButton.Name = "fileButton";
		this.fileButton.UseUnderline = true;
		this.fileButton.Label = global::Mono.Unix.Catalog.GetString ("Open file...");
		this.hbox7.Add (this.fileButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.fileButton]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox3.Add (this.hbox7);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.inputWindow = new global::Gtk.TextView ();
		this.inputWindow.CanFocus = true;
		this.inputWindow.Name = "inputWindow";
		this.GtkScrolledWindow1.Add (this.inputWindow);
		this.vbox3.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow1]));
		w8.Position = 1;
		this.vbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
		w9.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Homogeneous = true;
		this.hbox4.Spacing = 15;
		this.hbox4.BorderWidth = ((uint)(7));
		// Container child hbox4.Gtk.Box+BoxChild
		this.box2 = new global::Gtk.VBox ();
		this.box2.Name = "box2";
		this.box2.Spacing = 6;
		// Container child box2.Gtk.Box+BoxChild
		this.lexemeLabel = new global::Gtk.Label ();
		this.lexemeLabel.Name = "lexemeLabel";
		this.lexemeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Lexemes");
		this.box2.Add (this.lexemeLabel);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.box2 [this.lexemeLabel]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child box2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Homogeneous = true;
		// Container child hbox5.Gtk.Box+BoxChild
		this.lexemeWindow = new global::Gtk.ScrolledWindow ();
		this.lexemeWindow.CanFocus = true;
		this.lexemeWindow.Name = "lexemeWindow";
		this.lexemeWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child lexemeWindow.Gtk.Container+ContainerChild
		this.lexemeTree = new global::Gtk.TreeView ();
		this.lexemeTree.CanFocus = true;
		this.lexemeTree.Name = "lexemeTree";
		this.lexemeWindow.Add (this.lexemeTree);
		this.hbox5.Add (this.lexemeWindow);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lexemeWindow]));
		w12.Position = 0;
		this.box2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.box2 [this.hbox5]));
		w13.Position = 1;
		this.hbox4.Add (this.box2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.box2]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.box3 = new global::Gtk.VBox ();
		this.box3.Name = "box3";
		this.box3.Spacing = 6;
		// Container child box3.Gtk.Box+BoxChild
		this.symbolTableLabel = new global::Gtk.Label ();
		this.symbolTableLabel.Name = "symbolTableLabel";
		this.symbolTableLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Symbol Table");
		this.box3.Add (this.symbolTableLabel);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.box3 [this.symbolTableLabel]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child box3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Homogeneous = true;
		// Container child hbox6.Gtk.Box+BoxChild
		this.symbolTableWindow = new global::Gtk.ScrolledWindow ();
		this.symbolTableWindow.CanFocus = true;
		this.symbolTableWindow.Name = "symbolTableWindow";
		this.symbolTableWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child symbolTableWindow.Gtk.Container+ContainerChild
		this.symbolTableTree = new global::Gtk.TreeView ();
		this.symbolTableTree.CanFocus = true;
		this.symbolTableTree.Name = "symbolTableTree";
		this.symbolTableWindow.Add (this.symbolTableTree);
		this.hbox6.Add (this.symbolTableWindow);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.symbolTableWindow]));
		w17.Position = 0;
		this.box3.Add (this.hbox6);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.box3 [this.hbox6]));
		w18.Position = 1;
		this.hbox4.Add (this.box3);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.box3]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w20.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.executeButton = new global::Gtk.Button ();
		this.executeButton.CanFocus = true;
		this.executeButton.Name = "executeButton";
		this.executeButton.UseUnderline = true;
		this.executeButton.Label = global::Mono.Unix.Catalog.GetString ("EXECUTE");
		this.vbox2.Add (this.executeButton);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.executeButton]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.consoleLabel = new global::Gtk.Label ();
		this.consoleLabel.Name = "consoleLabel";
		this.consoleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Console");
		this.vbox2.Add (this.consoleLabel);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.consoleLabel]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.consoleEntry = new global::Gtk.Entry ();
		this.consoleEntry.CanFocus = true;
		this.consoleEntry.Name = "consoleEntry";
		this.consoleEntry.IsEditable = true;
		this.consoleEntry.InvisibleChar = '●';
		this.hbox3.Add (this.consoleEntry);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.consoleEntry]));
		w23.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.consoleSubmit = new global::Gtk.Button ();
		this.consoleSubmit.CanFocus = true;
		this.consoleSubmit.Name = "consoleSubmit";
		this.consoleSubmit.UseUnderline = true;
		this.consoleSubmit.Label = global::Mono.Unix.Catalog.GetString ("Submit");
		this.hbox3.Add (this.consoleSubmit);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.consoleSubmit]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.consoleField = new global::Gtk.TextView ();
		this.consoleField.CanFocus = true;
		this.consoleField.Name = "consoleField";
		this.GtkScrolledWindow.Add (this.consoleField);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w27.Position = 3;
		// Container child vbox2.Gtk.Box+BoxChild
		this.lexerStatus = new global::Gtk.Statusbar ();
		this.lexerStatus.Name = "lexerStatus";
		this.lexerStatus.Spacing = 6;
		// Container child lexerStatus.Gtk.Box+BoxChild
		this.creditsStatus = new global::Gtk.Statusbar ();
		this.creditsStatus.Name = "creditsStatus";
		this.creditsStatus.Spacing = 6;
		this.creditsStatus.HasResizeGrip = false;
		this.lexerStatus.Add (this.creditsStatus);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.lexerStatus [this.creditsStatus]));
		w28.PackType = ((global::Gtk.PackType)(1));
		w28.Position = 1;
		this.vbox2.Add (this.lexerStatus);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lexerStatus]));
		w29.Position = 4;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w30.Position = 3;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 883;
		this.DefaultHeight = 427;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.fileButton.Clicked += new global::System.EventHandler (this.OnFileButtonClicked);
		this.executeButton.Clicked += new global::System.EventHandler (this.OnExecuteButtonClicked);
	}
}
